#pragma once

#define MAX_BEAMS 256 // any more and you get console spam and game freezes (acutal max is 258 or 259 I think)
#define REC_BEAMS 8 // 8 * 32 players = 256
#define MAX_WEAPON_SLOT_POSITION 10
#define MIN_WEAPON_SLOT_POSITION 5
#define MAX_WEAPON_SLOT 5
#define REC_BULLETS_PER_SECOND 32 // max recommended bullets per second (shotgun has most BPS)

// weapon spawn flags
#define FL_WEP_SELECTONEMPTY 1
#define FL_WEP_NOAUTORELOAD 2
#define FL_WEP_NOAUTOSWITCHEMPTY 4
#define FL_WEP_LIMITINWORLD 8
#define FL_WEP_EXHAUSTIBLE 16
#define FL_WEP_HIDE_SECONDARY_AMMO 32
#define FL_WEP_LASER_SIGHT 64
#define FL_WEP_NO_JUMP 128
#define FL_WEP_WAIT_FOR_PROJECTILES 256
#define FL_WEP_EXCLUSIVE_HOLD 512

// mapper-placed weapon spawn flags
#define FL_DISABLE_RESPAWN 1024
#define FL_USE_ONLY 256

// shoot spawn flags
#define FL_SHOOT_IF_NOT_DAMAGE 1
#define FL_SHOOT_IF_NOT_MISS 2
#define FL_SHOOT_NO_MELEE_SOUND_OVERLAP 4
#define FL_SHOOT_RESPONSIVE_WINDUP 8
#define FL_SHOOT_PARTIAL_AMMO_SHOOT 16
#define FL_SHOOT_QUAKE_MUZZLEFLASH 32
#define FL_SHOOT_NO_AUTOFIRE 64
#define FL_SHOOT_PROJ_NO_ORIENT 128
#define FL_SHOOT_IN_WATER 256
#define FL_SHOOT_NO_BUBBLES 512
#define FL_SHOOT_DETONATE_SATCHELS 1024

// shoot effect flags
#define FL_EFFECT_EXPLOSION 1
#define FL_EFFECT_RICOCHET 2
#define FL_EFFECT_SPARKS 4
#define FL_EFFECT_LIGHTS 8
#define FL_EFFECT_BUBBLES_IN_AIR 16
#define FL_EFFECT_GUNSHOT_RICOCHET 32
#define FL_EFFECT_TARBABY 64
#define FL_EFFECT_TARBABY2 128
#define FL_EFFECT_BURST 256
#define FL_EFFECT_LAVA 512
#define FL_EFFECT_TELEPORT 1024

// User effect flags
#define FL_UEFFECT_USER_SOUNDS 1
#define FL_UEFFECT_KILL_ACTIVE 2

// shoot sound flags
#define FL_SOUND_NO_WATER_EFFECT 1

#define REVIVE_RADIUS 64.0f;

#define MAX_KV_ARRAY 16 // max array size per keyvalue

enum shoot_types
{
	SHOOT_BULLETS,
	SHOOT_MELEE,
	SHOOT_PROJECTILE,
	SHOOT_BEAM
};

enum tertiary_ammo_types
{
	TAMMO_NONE,
	TAMMO_SAME_AS_PRIMARY,
	TAMMO_SAME_AS_SECONDARY
};

enum spread_func
{
	SPREAD_GAUSSIAN,
	SPREAD_UNIFORM,
};

enum fire_mode
{
	PRIMARY,
	SECONDARY,
	TERTIARY
};

enum projectile_type
{
	PROJECTILE_ARGRENADE = 1,
	PROJECTILE_BANANA,
	PROJECTILE_BOLT,
	PROJECTILE_DISPLACER,
	PROJECTILE_GRENADE,
	PROJECTILE_HORNET,
	PROJECTILE_HVR,
	PROJECTILE_MORTAR,
	PROJECTILE_RPG,
	PROJECTILE_SHOCK,
	PROJECTILE_WEAPON,
	PROJECTILE_TRIPMINE,
	PROJECTILE_CUSTOM,
	PROJECTILE_OTHER
};

enum beam_type
{
	BEAM_DISABLED = -1,
	BEAM_LINEAR,
	BEAM_SPIRAL,
	BEAM_LINEAR_OPAQUE,
	BEAM_SPIRAL_OPAQUE,
	BEAM_PROJECTILE
};

enum user_beam_modes
{
	UBEAM_DISABLED,
	UBEAM_ATTACH_ATTACH,
	UBEAM_ATTACH_POINT,
	UBEAM_POINT_POINT,
};

enum explosion_types
{
	EXPLODE_SPRITE,
	EXPLODE_SPRITE_PARTICLES,
	EXPLODE_DISK,
	EXPLODE_CYLINDER,
	EXPLODE_TORUS
};

enum windup_ease
{
	EASE_NONE,
	EASE_IN,
	EASE_OUT,
	EASE_INOUT,
	EASE_IN_HEAVY,
	EASE_OUT_HEAVY,
	EASE_INOUT_HEAVY
};

enum windup_actions
{
	WINDUP_SHOOT_ON_RELEASE,
	WINDUP_SHOOT_ONCE,
	WINDUP_SHOOT_CONSTANT,
	WINDUP_SHOOT_ONCE_IF_HELD,
};

enum player_anim_refs
{
	ANIM_REF_CROWBAR, // also includes wrench for windups
	ANIM_REF_GREN,
	ANIM_REF_TRIP,
	ANIM_REF_ONEHANDED,
	ANIM_REF_PYTHON, // One Hnaded with more recoil
	ANIM_REF_SHOTGUN,
	ANIM_REF_GAUSS,
	ANIM_REF_MP5,
	ANIM_REF_RPG,
	ANIM_REF_EGON,
	ANIM_REF_SQUEAK,
	ANIM_REF_HIVE,
	ANIM_REF_BOW, // also includes scope animations
	ANIM_REF_MINIGUN,
	ANIM_REF_UZIS,
	ANIM_REF_M16, // also includes grenade launch anim (m203)
	ANIM_REF_SNIPER, // also includes scope animations
	ANIM_REF_SAW,
};

enum heal_modes
{
	HEAL_OFF,
	HEAL_FRIENDS,
	HEAL_FOES,
	HEAL_ALL,
	HEAL_REVIVE_FRIENDS,
	HEAL_REVIVE_FOES,
	HEAL_REVIVE_ALL,
};

enum hook_types
{
	HOOK_DISABLED,
	HOOK_PROJECTILE,
	HOOK_INSTANT
};

enum hook_modes
{
	HOOK_MODE_PULL,
	HOOK_MODE_PULL_LEAST_WEIGHT,
	HOOK_MODE_REPEL,
	HOOK_MODE_SWING,
};

enum hook_targets
{
	HOOK_EVERYTHING,
	HOOK_WORLD_ONLY,
	HOOK_MONSTERS_ONLY,
};

enum heal_targets
{
	HEALT_HUMANS,
	HEALT_ALIENS,
	HEALT_MACHINES,
	HEALT_BREAKABLES,
	HEALT_MACHINES_AND_BREAKABLES,
	HEALT_HUMANS_AND_ALIENS,
	HEALT_EVERYTHING,
};

enum shell_types
{
	SHELL_NONE,
	SHELL_SMALL,
	SHELL_LARGE,
	SHELL_SHOTGUN,
};

enum fire_actions
{
	FIRE_ACT_SHOOT,
	FIRE_ACT_LASER,
	FIRE_ACT_ZOOM,
	FIRE_ACT_ALT,
	FIRE_ACT_WINDUP
};

enum overcharge_actions
{
	OVERCHARGE_CONTINUE,
	OVERCHARGE_CANCEL,
	OVERCHARGE_SHOOT
};

enum primary_fire_modes
{
	PRIMARY_NO_CHANGE,
	PRIMARY_FIRE,
	PRIMARY_ALT_FIRE,
	PRIMARY_TOGGLE
};

enum projectile_follow_modes
{
	FOLLOW_NONE,
	FOLLOW_CROSSHAIRS,
	FOLLOW_ENEMIES,
};

enum reload_modes
{
	RELOAD_SIMPLE,
	RELOAD_STAGED,
	RELOAD_STAGED_RESPONSIVE,
	RELOAD_EFFECT_CHAIN
};

enum beam_alt_modes
{
	BEAM_ALT_DISABLED,
	BEAM_ALT_TOGGLE,
	BEAM_ALT_LINEAR,
	BEAM_ALT_LINEAR_TOGGLE,
	BEAM_ALT_EASE,
	BEAM_ALT_RANDOM
};
